type User @table {
  username: String!
  publicKey: String!
  email: String
  displayName: String
}

type Account @table {
  user: User!
  balance: Float!
  createdAt: Timestamp!
}

type Transaction @table {
  sender: User!
  receiver: User!
  amount: Float!
  timestamp: Timestamp!
  signature: String!
  description: String
  transactionType: String
}

type Block @table {
  blockNumber: Int!
  timestamp: Timestamp!
  hash: String!
  previousBlockHash: String!
  minerId: UUID
}